[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
debug_print = "1.0.0"
itertools = "0.13.0"
nom = "7.1.3"
num = "0.4.3"
rayon = "1.10.0"
